### ISSUE TITLE
Hi, question when i run adv_get_output.py

### ISSUE THREAD

**Issue by jsun94** [RU-System-Software-and-Security/NIC#6]
First of all I read good paper, thanks.

I'm trying to run NIC code.
When I run the _adv_get_output.py_ file, I'm having an error that,

> IOError: [Errno 2] No such file or directory: u'./results/advs_1.npy'

I can't find anyway that how can I get advs_1.npy file in the code.

I would appreciate it if you leave a reply, thank you.

**Comment by Jethro85** [comment]
> First of all I read good paper, thanks.
> 
> I'm trying to run NIC code.
> When I run the _adv_get_output.py_ file, I'm having an error that,
> 
> > IOError: [Errno 2] No such file or directory: u'./results/advs_1.npy'
> 
> I can't find anyway that how can I get advs_1.npy file in the code.
> 
> I would appreciate it if you leave a reply, thank you.

We re-use code from EvadeML-Zoo repo to generate adv examples. So here you need to use the EvadeML (or other tools) to generate adversarial examples of MNIST dataset and put them under the corresponding folder. The model we used is carlini_mnist_model. It is easy to generate adversarial examples according to their commands shown in their [repo](https://github.com/RU-System-Software-and-Security/NIC/tree/master/EvadeML-Zoo) (see their example).

**Comment by jsun94** [comment]
Thanks for your reply.

I think I made adversarial sample(dataset : MNIST, model : carlini), and got 'results' directory from EvadeML-Zoo repo.
I ran the main.py file to make the sample.

> python main.py --dataset_name MNIST --model_name carlini --nb_examples 2000 --balance_sampling --attacks "FGSM?eps=0.1;" --robustness "none;FeatureSqueezing?squeezer=bit_depth_1;" --detection "FeatureSqueezing?squeezers=bit_depth_1,median_filter_2_2&distance_measure=l1&fpr=0.05;"

But I don't have any .npy file.
> 'results/advs_1.npy'

Where can I get the .npy file??
Did I make wrong sample?

**Comment by Jethro85** [comment]
> Thanks for your reply.
> 
> I think I made adversarial sample(dataset : MNIST, model : carlini), and got 'results' directory from EvadeML-Zoo repo.
> I ran the main.py file to make the sample.
> 
> > python main.py --dataset_name MNIST --model_name carlini --nb_examples 2000 --balance_sampling --attacks "FGSM?eps=0.1;" --robustness "none;FeatureSqueezing?squeezer=bit_depth_1;" --detection "FeatureSqueezing?squeezers=bit_depth_1,median_filter_2_2&distance_measure=l1&fpr=0.05;"
> 
> But I don't have any .npy file.
> 
> > 'results/advs_1.npy'
> 
> Where can I get the .npy file??
> Did I make wrong sample?

It is not necessary to be a .npy file. You can save the adversarial examples in other kinds of files and use them here.
